POST http://localhost:4001/auth/registrar
Content-Type: application/json

{
    "nome": "José Inocêncio Lamartino Barros",
    "apelido": "Zé Inocêncio",
    "email": "zeinoc@zmail.com",
    "senha": "capiledarocha",
    "ativo": true,
    "autenticacao": false,
    "telefone": "+556195556599",
    "imagem": "http://imagem.de.teste"
}

###
POST http://localhost:4001/auth/login
Content-Type: application/json

{
    "email": "zeinoc@zmail.com",
    "senha": "capiledarocha"
}

###
POST http://localhost:4001/auth/recuperar-senha
Content-Type: application/json

{
    "email": "zeinoc@zmail.com"
}

###
POST http://localhost:4001/auth/redefinir-senha?token=465861a3f19b96877ca8c6816dab6958b9c7a12c53382b2683078a46632cc16d
Content-Type: application/json

{
    "novaSenha": "sundaymorning"
}