POST http://localhost:4001/auth/registrar
Content-Type: application/json

{
    "nome": "José Inocêncio Lamartino Barros",
    "apelido": "Zé Inocêncio",
    "email": "zeinoc@zmail.com",
    "senha": "capiledarocha",
    "ativo": true,
    "autenticacao": false,
    "telefone": "+556195556599",
    "imagem": "http://imagem.de.teste",
}